"""Four exact award products; alpha-only local derivatives preserve source pixels."""
import pathlib,json,hashlib,copy,re,importlib.util,xml.etree.ElementTree as ET
import numpy as np
from PIL import Image
R=pathlib.Path(__file__).resolve().parents[1];P=R/'public';E=R/'.runtime/award-australia-evidence';O=R/'research/award-country-expansion-2026-10-02'
spec=importlib.util.spec_from_file_location('m',R/'scripts/cutout-saldens-epica.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
D=json.load(open(P/'data/curated.json'));aw={str(b.get('untappdId')):b for b in D['beers']};brby={b['id']:b for b in D['breweries']};beers=[];breweries={};manifest=[]
EDEN=[[2,243,269],[4,229,277],[8,225,281],[16,223,281],[20,225,279],[26,227,277],[100,224,282],[150,220,287],[170,213,295],[190,199,307],[211,192,313],[270,193,314],[425,193,313],[461,196,309],[471,206,304],[476,222,291]]
EDWARD=[[82,381,416],[85,366,430],[95,357,434],[106,354,438],[114,360,434],[121,353,442],[129,356,440],[140,360,436],[220,355,442],[270,348,450],[330,335,464],[400,317,480],[460,301,497],[520,288,510],[575,283,516],[840,287,516],[869,295,509],[889,315,492],[901,349,459],[904,377,423]]
configs=[
 ('1524525','eden','/images/award-labels/1524525.jpeg','https://edenbrewery.beer/index.php/portfolio/birch-wit/','eden-product.html',5.5,12,'这款比利时风格小麦啤酒在官网列为5.5%酒精度、12 IBU，加入葵花籽、橙皮与芫荽籽。',EDEN),
 ('6000474','phoebe','/images/award-expansion/phoebe-retail.png','https://wildflowerbeer.com/products/st-phoebe-2024-ebony-sun-plum','phoebe.html',5.7,None,'2024年版本以桶陈金色混合发酵艾尔与 Ebony Sun 李子共同浸渍、再发酵四个月，随后瓶中自然增气。',None),
 ('6042204','walter','/images/award-expansion/walter-retail.png','https://wildflowerbeer.com/products/st-walter-2024-gamay','walter.html',6.2,None,'2024年 Gamay 版本以桶陈金色混合发酵艾尔与 Tumbarumba 的整串佳美葡萄浸渍、再发酵四个月，随后瓶中自然增气。',None),
 ('6216287','edward','/images/award-expansion/au-edward-image-original.png','https://wildflowerbeer.com/products/st-edward-2024','edward.html',6.8,None,'St Edward 的2024年版本使用 Montepulciano 葡萄；官方瓶装规格为750mL、6.8%酒精度，产品于2025年5月发布。',EDWARD)]
labels={x['id']:x for x in json.load(open(O/'label-cache.json'))['records']}
for uid,slug,raw,url,htmlfile,abv,ibu,description,spans in configs:
 b=copy.deepcopy(aw[uid]);br=copy.deepcopy(brby[b['breweryId']]);rp=P/raw.lstrip('/');im=Image.open(rp).convert('RGBA');arr=np.array(im)
 if spans: im.putalpha(m.make_mask(im.size,spans))
 assert np.array_equal(np.array(im)[:,:,:3],arr[:,:,:3]);full=P/f'images/award-expansion/au-{slug}-cutout.png';im.save(full)
 variants={}
 for kind,size in [('card',800),('map',320)]:
  d=im.copy();d.thumbnail((size,size),Image.Resampling.LANCZOS);fp=P/f'images/award-expansion/au-{slug}-{kind}.webp';d.save(fp,format='WEBP',lossless=True);variants[kind]=(d,fp)
 card,cp=variants['card'];a=np.array(card)[:,:,3];ys,xs=np.where(a>=64);padding=max(1,round(card.height*.01));x0=max(0,int(xs.min())-padding);y0=max(0,int(ys.min())-padding);x1=min(card.width,int(xs.max())+1+padding);y1=min(card.height,int(ys.max())+1+padding)
 imgurl=labels[uid]['url'] if slug=='eden' else ('https://maneliquor.com.au/cdn/shop/files/'+('WildflowerStPhoebe.png?v=1737359212' if slug=='phoebe' else 'WildflowerStWalter.png?v=1697158234')) if slug in ['phoebe','walter'] else 'https://wildflowerbeer.com/cdn/shop/files/IMG_2877_1.png?v=1746417124'
 imgpage='https://untappd.com/b/eden-brewery-birch-wit/1524525' if slug=='eden' else ('https://maneliquor.com.au/products/'+('wildflower-st-walter' if slug=='phoebe' else 'wildflower-tendency-to-rotate-each')) if slug in ['phoebe','walter'] else url
 b.update(abv=abv,ibu=ibu,description=description,descriptionBasis='official_product_description',image='/'+str(cp.relative_to(P)),imageOriginal='/'+str(full.relative_to(P)),imageThumbnail='/'+str(variants['map'][1].relative_to(P)),imageKind='product_packshot',imageSource=imgpage,imageDownloadUrl=imgurl,sourceImage=raw,imageContentBounds={'width':card.width,'height':card.height,'bounds':{'x':x0,'y':y0,'width':x1-x0,'height':y1-y0},'originalSha256':sha(cp),'method':'decoded_alpha_body_with_padding','alphaThreshold':64},imageEvidence={'sourceUrl':imgpage,'downloadUrl':imgurl,'sourceImage':raw,'sourceSha256':sha(rp),'sha256':sha(cp),'fullSha256':sha(full),'originalRGBunchanged':True,'individuallyVerified':True,'reviewedAt':'2026-10-02','method':'alpha_only_manual_outline' if spans else 'original_transparent_product_photo','parameters':{'rowSpans':spans},'derivative':{'cardMax':800,'mapMax':320,'format':'lossless_webp'}},identityEvidence={'status':'reviewed_same_product','sources':[f'https://awards.untappd.com/beers/{uid}/',url,imgpage],'basis':'Exact award product name, maker and for Wildflower the 2024 fruit variant matched to official product page. Bottle label design cross-checked; retail packshot does not establish a specific production batch.','reviewedAt':'2026-10-02'})
 b['descriptionEvidence']={'sourceUrl':url,'sourceFile':str((E/htmlfile).relative_to(R)),'sourceSha256':sha(E/htmlfile),'retrievedAt':'2026-10-02'};b['sourceUrls']=list(dict.fromkeys(b.get('sourceUrls',[])+[url,imgpage,imgurl]));b['sourceNote']='官网产品名称、年份/水果品种与获奖酒款精确核对。照片保留原像素；仅透明化背景及缩略。包装照片不是获奖年度具体批次证明。'
 if slug=='walter':b['sourceConflicts']=[{'field':'abv','officialValue':6.2,'retailerValue':6.3,'resolution':'official_product_value_retained','sourceUrl':imgpage}]
 place='Mittagong' if slug=='eden' else 'Marrickville';fn=place.lower()+'-osm.xml';node=ET.parse(E/fn).getroot().find('node');geo=f'https://www.openstreetmap.org/node/{node.attrib["id"]}'
 br.update(city=place,cityZh='米塔贡' if slug=='eden' else '马里克维尔',region='New South Wales',lat=float(node.attrib['lat']),lng=float(node.attrib['lon']),locationVerified=True,locationPrecision='city',locationRole='brewery_city_reference' if slug=='eden' else 'historical_brewery_city_reference',locationSourceUrl=url,coordinateSourceUrl=geo,locationNote='城市参考点，非精确厂址。'+('官网显示 Marrickville 场所已关闭；此处保留2024款的历史酒厂城市，不声称为当前营业地址。' if slug!='eden' else ''),locationEvidence={'identitySourceUrl':url,'identityEvidenceFile':str((E/htmlfile).relative_to(R)),'identitySha256':sha(E/htmlfile),'coordinateSourceUrl':geo,'coordinateSourcePageId':node.attrib['id'],'coordinateEvidenceFile':str((E/fn).relative_to(R)),'coordinateSha256':sha(E/fn),'coordinatePlaceTitle':place,'coordinateProvider':'OpenStreetMap','attribution':'© OpenStreetMap contributors, ODbL','verifiedAt':'2026-10-02'})
 breweries[br['id']]=br;beers.append(b);manifest.append({'beerId':b['id'],'sourceImage':raw,'sourceSha256':sha(rp),'image':'/'+str(full.relative_to(P)),'imageSha256':sha(full),'method':b['imageEvidence']['method'],'parameters':{'rowSpans':spans},'originalRGBunchanged':True,'reviewStatus':'approved'})
(O/'agent-award-australia.json').write_text(json.dumps({'metadata':{'createdAt':'2026-10-02','method':'official_product_facts_and_individually_reviewed_package_photos'},'breweries':list(breweries.values()),'beers':beers},ensure_ascii=False,indent=2)+'\n');(O/'australia-packshot-processing.json').write_text(json.dumps({'images':manifest},ensure_ascii=False,indent=2)+'\n');print('Australia',len(beers),'products',len(breweries),'cities')
