"""Four publicly documented beers at two real Siberian city references. Offline repeatable."""
import pathlib,json,hashlib,importlib.util,xml.etree.ElementTree as ET
import numpy as np
from PIL import Image,ImageDraw
R=pathlib.Path(__file__).resolve().parents[1];P=R/'public';E=R/'.runtime/award-country-evidence';O=R/'research/award-country-expansion-2026-10-02'
spec=importlib.util.spec_from_file_location('m',R/'scripts/cutout-saldens-epica.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
SPANS=[[.080,.490,.518],[.083,.472,.541],[.096,.465,.548],[.102,.468,.546],[.115,.467,.548],[.131,.469,.547],[.138,.472,.544],[.200,.466,.551],[.320,.452,.563],[.370,.444,.567],[.395,.430,.581],[.420,.417,.594],[.445,.409,.602],[.474,.405,.604],[.540,.406,.604],[.840,.406,.604],[.872,.409,.600],[.892,.418,.592],[.896,.443,.575],[.897,.470,.540]]
beers=[];breweries=[];images=[]
for key,name,city,cityZh,aliases,region,identity,identityfile in [('gusi','GUSI Brewery','Novosibirsk','新西伯利亚',['Новосибирск','Akademgorodok','Академгородок','西伯利亚'],'Novosibirsk Oblast','https://beergusi.ru/','gusi.html'),('salek','SALEK Real Craft Brewery','Krasnoyarsk','克拉斯诺亚尔斯克',['Красноярск','西伯利亚'],'Krasnoyarsk Krai','https://salek.pro/oktoberfest','salek.html')]:
 fn=city.lower()+'-osm.xml';node=ET.parse(E/fn).getroot().find('node');geo='https://www.openstreetmap.org/node/'+node.attrib['id'];tags={t.attrib['k']:t.attrib['v'] for t in node.findall('tag')};assert tags.get('place')=='city';assert tags.get('name:en')==city
 breweries.append({'id':'siberia-'+key,'name':name,'country':'Russia','countryCode':'RU','countryZh':'俄罗斯','countryBasis':'official_brewery_location','city':city,'cityZh':cityZh,'cityAliases':aliases,'region':region,'regionZh':'西伯利亚','lat':float(node.attrib['lat']),'lng':float(node.attrib['lon']),'locationVerified':True,'locationPrecision':'city','locationRole':'brewery_city_reference','locationNote':'官网明确酒厂所在城市；地图采用同城 OSM 城市参考点，不是逐款精确生产厂房坐标。','locationSourceUrl':identity,'coordinateSourceUrl':geo,'locationEvidence':{'identitySourceUrl':identity,'identityEvidenceFile':str((E/identityfile).relative_to(R)),'identitySha256':sha(E/identityfile),'coordinateSourceUrl':geo,'coordinateEvidenceFile':str((E/fn).relative_to(R)),'coordinateSha256':sha(E/fn),'coordinateSourcePageId':node.attrib['id'],'coordinatePlaceTitle':city,'coordinateProvider':'OpenStreetMap','attribution':'© OpenStreetMap contributors, ODbL','verifiedAt':'2026-10-02'},'sourceUrls':[identity,geo],'collection':'regional','collections':['regional']})
items=[('gusi-rolling','Rolling Waves','gusi','Czech Lager',4.7,19,'双煎煮法酿造的捷克风格拉格，官网描述为麦芽感、柔和苦味与萨兹酒花香气。','png','https://beergusi.ru/','gusi.html','https://static.tildacdn.com/tild3436-6538-4861-b739-663465326139/noroot.png','1075136'),('gusi-dark','Dark Island','gusi','Oatmeal Milk Stout',5.9,None,'加入燕麦片、乳糖与马达加斯加香草荚的牛奶世涛，官网描述其口感柔和、奶油般顺滑。','png','https://beergusi.ru/','gusi.html','https://static.tildacdn.com/tild3834-6437-4935-b733-663531343066/noroot.png','2974410'),('salek-apa','SALEK APA','salek','American Pale Ale',5.2,30,'使用 Citra 与 Simcoe 酒花的美式淡色艾尔，酒厂描述其柑橘香气鲜明、苦味柔和。','jpg','https://salek.pro/catalog/salek-apa','salek-apa.html','https://static.tildacdn.com/tild6432-3663-4264-b365-636430383239/APA.jpg',None),('salek-ipa','SALEK IPA','salek','India Pale Ale',5.8,40,'酒厂介绍其带有焦糖与热带水果香气，包含葡萄柚、桃与百香果气息，收尾有明显苦味。','jpg','https://salek.pro/catalog/salek-ipa','salek-ipa.html','https://static.tildacdn.com/tild6237-3165-4335-b233-623536326430/IPA.jpg',None)]
for slug,name,brand,style,abv,ibu,desc,ext,url,htmlfile,imgurl,uid in items:
 raw=P/f'images/country-expansion/{slug}.{ext}';im=Image.open(raw).convert('RGBA');rgb=np.asarray(im)[:,:,:3].copy();method='official_transparent_packshot';params={}
 if brand=='salek':
  controls=[[y*im.height,l*im.width,r*im.width] for y,l,r in SPANS];im.putalpha(m.make_mask(im.size,controls));method='local_python_alpha_only_reviewed_outline';params={'normalizedRowSpans':SPANS}
 assert np.array_equal(rgb,np.asarray(im)[:,:,:3]);full=P/f'images/country-expansion/{slug}-cutout.png';im.save(full)
 variants={}
 for kind,size in [('card',800),('map',320)]:
  d=im.copy();d.thumbnail((size,size),Image.Resampling.LANCZOS);fp=P/f'images/country-expansion/{slug}-{kind}.webp';d.save(fp,format='WEBP',lossless=True);variants[kind]=(d,fp)
 card,cp=variants['card'];a=np.asarray(card)[:,:,3];ys,xs=np.where(a>=64);pad=max(1,round(card.height*.01));x=max(0,int(xs.min())-pad);y=max(0,int(ys.min())-pad);right=min(card.width,int(xs.max())+1+pad);bottom=min(card.height,int(ys.max())+1+pad)
 b={'id':'siberia-'+slug,'name':name,'breweryId':'siberia-'+brand,'collection':'regional','collections':['regional'],'style':style,'abv':abv,'ibu':ibu,'description':desc,'descriptionBasis':'official_product_description','flavors':[],'hops':[],'malts':[],'rating':None,'ratingsCount':None,'awards':[],'image':'/'+str(cp.relative_to(P)),'imageOriginal':'/'+str(full.relative_to(P)),'imageThumbnail':'/'+str(variants['map'][1].relative_to(P)),'sourceImage':'/'+str(raw.relative_to(P)),'imageKind':'product_packshot','imageSource':url,'imageDownloadUrl':imgurl,'imageCredit':brand.upper()+' official product catalogue','imageLicense':'Copyright holder; no open image licence stated','imageContentBounds':{'width':card.width,'height':card.height,'bounds':{'x':x,'y':y,'width':right-x,'height':bottom-y},'originalSha256':sha(cp),'method':'decoded_alpha_body_with_padding','alphaThreshold':64},'imageEvidence':{'sourceUrl':url,'downloadUrl':imgurl,'sourceImage':'/'+str(raw.relative_to(P)),'sourceSha256':sha(raw),'sha256':sha(cp),'fullSha256':sha(full),'method':method,'parameters':params,'originalRGBunchanged':True,'individuallyVerified':True,'reviewedAt':'2026-10-02','derivative':{'cardMax':800,'mapMax':320,'format':'lossless_webp'}},'descriptionEvidence':{'sourceUrl':url,'sourceFile':str((E/htmlfile).relative_to(R)),'sourceSha256':sha(E/htmlfile),'retrievedAt':'2026-10-02'},'sourceUrls':[url,imgurl],'sourceNote':'西伯利亚真实城市的官网产品；原始照片保留，仅本地alpha背景分离及缩略，不推断销量或获奖。'}
 if uid:b['untappdId']=uid;b['sourceUrls'].append('https://untappd.com/b/gusi-'+('rolling-waves' if slug=='gusi-rolling' else 'dark-island')+'/'+uid);b['identityEvidence']={'status':'official_outbound_product_id','basis':'Official brewery product section directly links to this exact Untappd product ID.','sourceUrl':url}
 if slug=='gusi-dark':b['sourceConflicts']=[{'field':'ibu','officialPageValue':19,'officialPackshotValue':22,'resolution':'null_until_version_confirmed','sourceUrl':url}];b['sourceNote']+=' 官网文字IBU19与原罐标22不一致，IBU留空，不混用版本。'
 beers.append(b);images.append({'beerId':b['id'],'sourceImage':b['sourceImage'],'sourceSha256':sha(raw),'image':b['imageOriginal'],'imageSha256':sha(full),'originalRGBunchanged':True,'method':method,'parameters':params,'reviewStatus':'approved'})
(P/'data/siberia-expansion.json').write_text(json.dumps({'metadata':{'createdAt':'2026-10-02','method':'official_public_product_pages','scope':'four products at two Siberian city references','status':'ready'},'breweries':breweries,'beers':beers},ensure_ascii=False,indent=2)+'\n');(O/'siberia-packshot-processing.json').write_text(json.dumps({'images':images},ensure_ascii=False,indent=2)+'\n')
sheet=Image.new('RGB',(1200,620),(32,41,48));d=ImageDraw.Draw(sheet)
for i,b in enumerate(beers):
 im=Image.open(P/b['image'].lstrip('/')).convert('RGBA');im=im.crop(im.getbbox());im.thumbnail((270,560));sheet.paste(im,(i*300+(300-im.width)//2,40),im);d.text((i*300+10,10),b['name'],fill='white')
sheet.save(E/'siberia-review.jpg');print(len(beers),'products',len(breweries),'verified cities')
