// Representative crop regions, researched 2026-10-02. These are deliberately
// approximate regional map anchors, never farm coordinates or beer suppliers.
export const INGREDIENT_REGION_NOTES = Object.freeze({
  checkedAt: '2026-10-02',
  scope: '酿酒原料代表种植产区，并非全球全部产区或任一酒款的采购来源。',
  coordinates: '坐标是产区内城市附近的区域示意点，取一位小数；不是田块、农场、厂址或产区边界。',
  climate: '气候文字是作物生长的一般要求或区域农技资料；不是当天天气的适种评分，也不能替代当地农艺判断。',
  seasons: '季节文字区分典型生长采收窗口与已注明的现场观察，月份均为当地公历；品种、播期、海拔及雨季变化会影响实际日期，不是实时天气或逐农场预测。',
  use: '大麦、小麦、燕麦、黑麦先是农作物；是否制麦或用于酿酒取决于品种、质量与加工。柑橘、芫荽、咖啡、可可是可选辅料。',
  exclusions: '水和酵母没有被标为种植产区。',
});

export const INGREDIENT_TYPES = Object.freeze([
  { id: 'barley', labelZh: '麦芽大麦', cropNameZh: '大麦', role: 'base' },
  { id: 'hops', labelZh: '啤酒花', cropNameZh: '啤酒花', role: 'base' },
  { id: 'wheat', labelZh: '小麦', cropNameZh: '小麦', role: 'grain' },
  { id: 'oats', labelZh: '燕麦', cropNameZh: '燕麦', role: 'grain' },
  { id: 'rye', labelZh: '黑麦', cropNameZh: '黑麦', role: 'grain' },
  { id: 'citrus', labelZh: '柑橘皮', cropNameZh: '柑橘', role: 'adjunct' },
  { id: 'coriander', labelZh: '芫荽籽', cropNameZh: '芫荽', role: 'adjunct' },
  { id: 'coffee', labelZh: '咖啡', cropNameZh: '咖啡', role: 'adjunct' },
  { id: 'cocoa', labelZh: '可可', cropNameZh: '可可', role: 'adjunct' },
].map(Object.freeze));

const SOURCES = {
  tonoHops: 'https://www.kirin.co.jp/journal/alcohol/stories/20240829_01/',
  tonoHarvest: 'https://rd.kirinholdings.com/domain/result/story_008.html',
  limpopoCitrus: 'https://www.ldard.gov.za/images/documents/Notices/UPDATED%20RAAVC%20PLAN%2029%20NOV%2000_33.pdf',
  arsiBarley: 'https://icarda.org/media/news/building-resilient-and-gainful-livelihoods-barley',
  arsiSeason: 'https://www.sciencepublishinggroup.com/article/10.11648/j.ijaas.20220801.17',
  buenosAiresBarley: 'https://www.argentina.gob.ar/node/199177',
  argentinaBarleyHarvest: 'https://www.argentina.gob.ar/sites/default/files/sisa_cebada_22_23_v1.pdf',
  huilaCoffee: 'https://huila.federaciondecafeteros.org/listado-noticias/huila-mantuvo-su-produccion-de-cafe-en-marzo/',
  sanMartinCocoa: 'https://www.gob.pe/institucion/regionsanmartin-dra/noticias/1191653-goresam-elabora-hoja-de-ruta-para-rendimientos-sostenibles-e-inclusivos-en-el-cultivo-de-cacao-en-la-region-san-martin',
  sanMartinSeason: 'https://www.senamhi.gob.pe/load/file/02953SENA-131.pdf',
  altaiWheat: 'https://specagro.ru/news/202503/v-rossii-v-2024-godu-sobrali-rekordnye-24-mln-t-tverdoy-pshenicy-ekspert',
  altaiHarvest: 'https://www.specagro.ru/analytics/202509/daydzhest-zernovye-minselkhoz-rf-sokhranyaet-prognoz-po-sboru-zerna-v-2025-godu-na',
  rwenzoriCoffee: 'https://ugandacoffee.go.ug/sites/default/files/2024-07/Uganda%20Coffee%20Exporting%20Company%20Profiles%20Catalogue%20%2BQRCode.2024.pdf',

  canadaBarley: 'https://www.grainscanada.gc.ca/en/grain-research/grain-harvest-export-quality/barley/2025/summary-conditions-production.html',
  waBarley: 'https://www.agric.wa.gov.au/sites/gateway/files/DPIRD_CSG%202024_Barley.pdf',
  scotlandBarley: 'https://www.gov.scot/publications/cereal-and-oilseed-rape-harvest-2023-final-estimates/pages/composition-of-cereal-production-in-2023/',
  scotlandCrops: 'https://www.gov.scot/publications/cereal-and-oilseed-rape-harvest-final-estimates-2024/pages/introduction/',
  scotlandMap: 'https://www.gov.scot/binaries/content/documents/govscot/publications/statistics/2021/05/scottish-crop-map-2019-2/documents/scottish-crop-map-2019/scottish-crop-map-2019/govscot%3Adocument/scottish-crop-map-2019.pdf',
  coolGrains: 'https://extension.umn.edu/agriculture/crop-production/small-grains/late-planting-spring-small-grains',
  grainHeat: 'https://blog-crop-news.extension.umn.edu/2021/06/heat-stress-on-small-grains.html',
  yakima: 'https://www.usahops.org/img/blog_pdf/320.pdf',
  hopSeason: 'https://www.usahops.org/enthusiasts/growing-season.html',
  hopDaylight: 'https://lfl.bayern.de/ipz/hopfen/323531/index.php',
  hallertau: 'https://www.lfl.bayern.de/ipz/hopfen/359755/index.php',
  saaz: 'https://whc.unesco.org/en/list/1558/',
  nzHops: 'https://nzhops.co.nz/',
  nzHopsRegions: 'https://www.venture.org.nz/assets/Uploads/Hops-Blueprint-Final.pdf',
  kansas: 'https://www.nass.usda.gov/Quick_Stats/Ag_Overview/stateOverview.php?state=Kansas&year=2025',
  punjab: 'https://pau.edu/index.php?DO=viewEventDetail&_act=manageEvent&dataE=datae&intID=12055',
  nswWheat: 'https://www.dpi.nsw.gov.au/about-us/publications/pdi/2025/wheat',
  nswSowing: 'https://www.dpi.nsw.gov.au/__data/assets/pdf_file/0003/1546050/2024-WCVSG-V1-WEB-22Mar24.pdf',
  saskOats: 'https://dashboard.saskatchewan.ca/agriculture/seeding-progress/seeding-oats',
  waOats: 'https://grdc.com.au/__data/assets/pdf_file/0021/370560/GrowNote-Oats-West-0A-Introduction.pdf',
  waOatsClimate: 'https://grdc.com.au/__data/assets/pdf_file/0025/370573/GrowNote-Oats-West-14-Environment.pdf',
  brandenburg: 'https://agrarbericht.brandenburg.de/abo/de/produktion/spitzenplaetze/',
  brandenburgTrials: 'https://lelf.brandenburg.de/lelf/de/landwirtschaft/acker-und-pflanzenbau/landessortenwesen/',
  minnesotaGrains: 'https://extension.umn.edu/agriculture/crop-production/small-grains',
  ryeClimate: 'https://extension.umn.edu/agriculture/crop-production/cover-crops/getting-started-with-cover-crops',
  valencia: 'https://pegv.gva.es/auto/scpd/web/60101Cultivo/aecv00143_c.html',
  citrusSites: 'https://ask.ifas.ufl.edu/publication/CH024',
  citrusCold: 'https://ask.ifas.ufl.edu/publication/cg095',
  kota: 'https://indianspices.com/indianspices/locations/spices-park-kota-rajasthan.html',
  kotaGrowing: 'https://www.tourism.rajasthan.gov.in/content/dam/agriculture/Rajasthan%20Agricultural%20Competitiveness%20Project/ABPFTechDPR/RACP_ABPF_Tech%20DPR_Coriander%20Powder%20Unit.pdf',
  corianderIndia: 'https://www.agritech.tnau.ac.in/horticulture/horti_spice%20crops_corinader.html',
  corianderCanada: 'https://www.saskatchewan.ca/business/agriculture-natural-resources-and-industry/agribusiness-farmers-and-ranchers/crops-and-irrigation/field-crops/specialty-crops/herbs-and-spices/coriander',
  minas: 'https://www.emater.mg.gov.br/portal.do/site-noticias/circuito-mineiro-da-cafeicultura-2025-vai-passar-por-22-municipios-mineiros/?flagweb=novosite_pagina_interna_noticia&id=29105',
  coffeeClimate: 'https://www.ico.org/documents/cy2016-17/sc-75e-review-studies-climate-change.pdf',
  dakLak: 'https://www.ipvietnam.gov.vn/web/english/domestic-ip-activities/-/asset_publisher/ZMuTgR44COLR/content/amendment-of-geographical-indication-registration-certificate-buon-ma-thuot-for-coffee-products',
  puer: 'https://www.yn.gov.cn/ztgg/tjzfgmjqjgxnjs/gcls/202401/t20240105_293059.html',
  yunnanCoffee: 'https://nync.yn.gov.cn/html/2023/gongshigonggao_0922/400849.html',
  cocoaClimate: 'https://www.icco.org/growing-cocoa/',
  ghana: 'https://cocobod.gh/resource_files/june-2017.pdf',
  ghanaWest: 'https://cocobod.gh/news/cocobod-western-north-police-command-partner-to-tackle-cocoa-smuggling',
  soubre: 'https://www.anader.ci/lutte-contre-le-swollen-shoot-lanader-et-le-conseil-du-cafe-cacao-mobilises-aux-cotes-des-producteurs-de-liliyo-soubre/',
  ecuador: 'https://repositorio.iniap.gob.ec/bitstream/41000/5417/4/iniapeetpGA002.pdf',
  saskHarvest: 'https://www.saskatchewan.ca/government/news-and-media/2025/september/11/crop-report-for-the-period-september-2-to-september-8-2025',
  waSowing: 'https://nvt.grdc.com.au/__data/assets/pdf_file/0026/612647/DPIRD-2025-WA-Crop-Sowing-Guide-20241106.pdf',
  waOatSowing: 'https://grdc.com.au/__data/assets/pdf_file/0020/443513/2021-GRDC-Grains-Research-Update-Program-Book-Perth.pdf',
  scotlandSpring: 'https://www.fas.scot/article/crop-health-update/',
  scotlandHarvest: 'https://blogs.gov.scot/statistics/2017/12/13/scotlands-cereal-harvest-2017/',
  scotlandOatSowing: 'https://www.gov.scot/publications/cereal-oilseed-rape-harvest-2021-final-estimates/pages/7/',
  hallertauHarvest: 'https://www.lfl.bayern.de/publikationen/informationen/040140/index.php',
  czechHopHarvest: 'https://www.chizatec.cz/download/page42089.pdf',
  kansasCalendar: 'https://www.kansashistory.gov/kansapedia/wheat/12235',
  punjabSowing: 'https://pau.edu/index.php?DO=viewEventDetail&_act=manageEvent&intID=6993',
  punjabHarvest: 'https://pau.edu/index.php?DO=viewEventDetail&_act=manageEvent&dataE=&intID=12348',
  nswSowingResearch: 'https://researchoutput.csu.edu.au/en/publications/yield-responses-to-sowing-date-in-southern-nsw-one-cultivar-doesn/',
  brandenburgRyeSowing: 'https://www.nutrinet.agrarpraxisforschung.de/praxisforschung/praxisversuche/netzwerkversuche/weisskleebeisaat-in-winterroggen',
  minnesotaWinterSowing: 'https://blog-crop-news.extension.umn.edu/2018/09/tips-for-planting-winter-cereals.html',
  valenciaCalendar: 'https://ivia.gva.es/documents/161862582/162348673/calendarios_recoleccion_general.pdf/3cfb1c16-22a8-40cd-8c57-ceae070b3fce',
  floridaCalendar: 'https://ask.ifas.ufl.edu/publication/HS132',
  floridaFlowering: 'https://ask.ifas.ufl.edu/publication/CG091',
  minasHarvest: 'https://www.agenciaminas.mg.gov.br/noticia/epamig-orienta-produtores-para-colheita-do-cafe',
  ethiopiaCalendar: 'https://www.climatehubs.usda.gov/sites/default/files/Publication-Kew%20Coffee%20Farming%20and%20Climate%20Change%20in%20Ethiopia.pdf',
  dakLakCalendar: 'https://congbao.daklak.gov.vn/FileCongBao/1495_6243.pdf',
  puerHarvest: 'https://nync.yn.gov.cn/html/2022/zhoushilianbo-new_1114/392401.html',
  cocoaCalendar: 'https://www.icco.org/faq/',
  akmolaGrainGuide: 'https://www.gov.kz/uploads/2024/4/23/ab845f482959375858f3587da9204869_original.1526871.pdf',
  akmolaBarley: 'https://stat.gov.kz/upload/iblock/f18/39554fiumdp0brd3cqyutk1gh2z1h9u4/%D0%A1-06-%D0%93%20%28%D0%B0%D0%BD%D0%B3%29.pdf',
  novosibirskOats: 'https://specagro.ru/news/202606/v-novosibirskoy-oblasti-zaseyano-18-mln-ga-yarovymi-kulturami',
  georgeHops: 'https://www.nda.gov.za/images/News%20Letters/DALRRD%20News%20Letters/newsletters-2023/dalrrdnews-april-2023.pdf',
  georgeWater: 'https://www.sab.co.za/node/88/revisions/661/view',
  harveyCitrus: 'https://www.harvey.wa.gov.au/wp-content/uploads/2025/08/Invest-Harvey-Region-Final.pdf',
  waCitrusSeason: 'https://wacitrus.com.au/our-fruit/harvest-season/',
  elBolsonHops: 'https://rionegro.gov.ar/articulo/48576/comienza-la-cosecha-de-lupulo-en-el-bolson',
  elBolsonClimate: 'https://www.argentina.gob.ar/sites/default/files/agenda_territorial_de_el_bolson.pdf',
  passoFundoOats: 'https://www.alice.cnptia.embrapa.br/alice/bitstream/doc/1067851/1/ID440212016TSjossana.pdf',
  yanqiHops: 'https://www.chinacoop.gov.cn/HTML/2017/09/18/123586.html',
  yanqiHopHarvest: 'https://www.xinhuanet.com/photo/20240910/470c8fc61f164c8cb602431285ce50fb/c.html',
  yanqiLocation: 'https://www.maiji.gov.cn/info/1301/217481.htm',
  yumenHops: 'https://gansu.gscn.com.cn/system/2024/09/20/013205578.shtml',
  yanchengBarley: 'https://snw.yancheng.gov.cn/art/2020/6/1/art_24595_3378349.html',
  chinaBarleyGuide: 'https://zzys.moa.gov.cn/gzdt/201904/t20190425_6310363.htm',
  hulunbuirBarley: 'https://www.crbeer.com.hk/responsibilityReport/2025-07-04/b4c63ba6-c3d6-41fc-8939-bd2006a4feab.pdf',
  hulunbuirHarvest: 'https://m.21jingji.com/article/20240423/8395bd78349e695a5e60a124245ce7b3.html',
  baoshanCoffee: 'https://nync.yn.gov.cn/html/2024/hudianxiezuo_1126/1416192.html',
  baoshanWinterHarvest: 'https://swt.yn.gov.cn/swxx/202512/t20251205_3217707.html',
  baoshanSpringHarvest: 'https://baoshan.gov.cn/info/1032/10343964.htm',
  xinglongCocoa: 'https://www.catas.cn/contents/3217/229413.html',
  xinglongCocoaHarvest: 'https://www.catas.cn/contents/8/241682.html',
};

// Crop calendars are separate from reported local harvest observations; neither
// is current weather or a suitability score. Country-wide calendars also carry
// their own scope, rather than pretending to measure a specific field.
const SEASONS = {
  'hops-tono': ['春夏攀藤生长、夏末按球花成熟度采收；远野田间报道记录8月下旬采花，不能据单年观察确定所有品种的固定采期。', ['tonoHarvest'], 'regional_crop_observation'],
  'citrus-limpopo': ['南半球冬末至春季分批采收；省级农业资料将Valencia橙的主要采期列为7—9月，其他柑橘品种不能直接套用。', ['limpopoCitrus']],
  'barley-arsi': ['阿尔西Lemu-Bilbilo试验记录6—12月为大麦种植观察周期；这是特定地点和年份的试验记录，不能当作整个产区固定播收日期。', ['arsiSeason'], 'regional_crop_observation'],
  'barley-buenosaires': ['南半球冬季6—7月按品种播种、冬春生长；参照阿根廷一般作期，收获从11月延至12月或翌年1月初。', ['buenosAiresBarley', 'argentinaBarleyHarvest'], 'country_crop_calendar'],
  'coffee-huila': ['当地正常年份有两段较集中的采收期：4—6月及9—12月；雨季异常会使成熟与采摘分散，各海拔需按熟果分批采收。', ['huilaCoffee']],
  'cocoa-sanmartin': ['当地农气观察记录4月下旬多站可可处于成熟阶段；这是特定年份物候记录，不能作为全省统一采期，成熟果应分批采摘。', ['sanMartinSeason'], 'regional_crop_observation'],
  'wheat-altai': ['当地8月底已有新季小麦收获与检验记录；该观察不表示所有地区、品种的完整采收窗口，实际成熟仍受播期和气候影响。', ['altaiHarvest'], 'regional_crop_observation'],
  'coffee-rwenzori': ['当地供应商在咖啡局资料中将鲁文佐里采收期列为10—12月；按山地海拔和熟果分批采摘，该窗口不代表乌干达全国作期。', ['rwenzoriCoffee']],

  'barley-saskatchewan': ['春播、夏季抽穗灌浆，夏末至秋季收获；春雨和秋雨会使播收时间提前或推迟。', ['canadaBarley', 'saskHarvest']],
  'barley-western-australia': ['南半球秋季4—5月是重要播种窗口，冬春生长；播期需按品种及降雨调整，兼顾霜冻和后期干热。', ['waSowing']],
  'barley-scotland': ['春大麦通常春季播种、春夏生长；谷物收获多在8—9月，湿冷春季会推迟播种。', ['scotlandSpring', 'scotlandHarvest']],
  'hops-yakima': ['春季萌芽攀藤，夏季形成球花；采收约从8月中下旬延续至10月初，依品种分批进行。', ['hopSeason']],
  'hops-hallertau': ['春夏生长，典型采收窗口为8月底至9月中下旬；具体日期要结合品种和球花成熟度。', ['hallertauHarvest']],
  'hops-saaz': ['春夏生长、夏末至初秋采收；捷克不同啤酒花品种的成熟窗口可从8月延续到9月。', ['czechHopHarvest']],
  'hops-nelson': ['南半球春季9月起整理搭藤，春夏旺长；通常2月下旬开始采收，3月为主要采收期。', ['nzHopsRegions']],
  'wheat-kansas': ['9—10月秋播并越冬，次年春季恢复生长；通常6月中下旬至7月初收获。', ['kansasCalendar']],
  'wheat-punjab': ['秋末播种、冬季生长，春季进入收获；当地4月已有麦收，适时播种有助避开成熟后期热胁迫。', ['punjabSowing', 'punjabHarvest']],
  'wheat-nsw': ['南半球4—5月秋播、冬春生长，春季开花，11—12月前后收获；快熟与慢熟品种的播期不同。', ['nswSowingResearch', 'nswSowing', 'nswWheat']],
  'oats-saskatchewan': ['春季播种、夏季生长，夏末至秋季成熟采收；实际进度随当年雨水和品种变化。', ['saskOats', 'saskHarvest']],
  'oats-scotland': ['当地燕麦多为春播，春夏生长，谷物收获通常在8—9月；成熟和收获受降雨影响。', ['scotlandOatSowing', 'scotlandHarvest']],
  'oats-wa': ['南半球秋播、冬春生长，4—5月播期需结合品种选择；籽粒用和干草用燕麦的收获阶段不同。', ['waOatSowing', 'waOats']],
  'rye-brandenburg': ['冬黑麦秋播并越冬，次年春季继续生长；当地试验的播种窗口在9月下旬至10月上旬。', ['brandenburgRyeSowing']],
  'rye-minnesota': ['秋播越冬，播期多在9月，州南部可延至10月；春季恢复生长，籽粒通常夏季收获。', ['minnesotaWinterSowing', 'ryeClimate']],
  'citrus-valencia': ['柑橘依早、中、晚熟品种错峰采收，跨越秋冬至翌年春季，部分晚熟品种延至初夏。', ['valenciaCalendar']],
  'citrus-florida': ['通常3月前后盛花；橙类按早、中、晚熟品种，从10月至翌年6月分批收获。', ['floridaFlowering', 'floridaCalendar']],
  'coriander-kota': ['凉季作物，通常10—11月播种、冬季生长；新季芫荽籽在2—3月集中上市。', ['kotaGrowing']],
  'coriander-saskatchewan': ['4月下旬至5月中旬春播、夏季生长；大粒型约需100—110天生长季，小粒型更长，种子成熟后采收。', ['corianderCanada']],
  'coffee-minas': ['南半球秋冬约5月起进入采收，常持续至7—8月；按咖啡果成熟度分批采摘。', ['minasHarvest']],
  'coffee-sidama': ['按埃塞俄比亚咖啡区的一般作期，2—5月初雨促进开花坐果；10月至翌年1—2月长干季适逢采收加工，具体随海拔和雨季变化。', ['ethiopiaCalendar'], 'country_crop_calendar'],
  'coffee-daklak': ['邦美蜀咖啡通常10—12月分批采熟果；干季仍需供水，宜按当地雨旱季理解生长周期。', ['dakLakCalendar']],
  'coffee-puer': ['秋末冬初开始鲜果采摘；各批次按果实成熟度采收，海拔与降雨会影响具体时间。', ['puerHarvest']],
  'cocoa-ghana': ['按加纳国别作期，主采收约9月至翌年3月，中季约5—8月；实际随雨旱季及成熟批次变化。', ['cocoaCalendar'], 'country_crop_calendar'],
  'cocoa-soubre': ['按科特迪瓦国别作期，主采收约10月至翌年3月，中季约5—8月；实际随雨季和成熟批次变化。', ['cocoaCalendar'], 'country_crop_calendar'],
  'cocoa-losrios': ['按厄瓜多尔国别作期，主采收约3—6月，中季约10月至翌年2月；赤道附近宜按雨旱季与成熟批次理解。', ['cocoaCalendar'], 'country_crop_calendar'],
  'barley-akmola': ['春播、夏季生长；当地2024年农技指南将大麦播期列为5月底至6月初，各土壤气候分区略有差异，不能视为每年固定日期。', ['akmolaGrainGuide']],
  'oats-novosibirsk': ['当地种植春播燕麦，春末至初夏播种、夏季生长；官方6月播种进度可作季节参考，具体播期随春季天气和土壤条件调整。', ['novosibirskOats', 'coolGrains']],
  'hops-george': ['南半球夏末2—3月集中采收，政府农情资料记录约六周采期；具体采收时间仍随品种、成熟情况与当地管理变化。', ['georgeHops']],
  'citrus-harvey': ['南半球5—12月为主要柑橘季，冬季较集中；夏橙等品种可延伸至夏季，应依品种区分采收窗口。', ['harveyCitrus', 'waCitrusSeason']],
  'hops-elbolson': ['南半球8月底至9月萌发生长，10—11月旺长；夏末2月底至3月前后按球花成熟度分批采收。', ['elBolsonHops']],
  'oats-passofundo': ['南半球5—6月播种、冬季生长，春季进入成熟；当地试验约9—10月成熟，日期随品种与播期变化。', ['passoFundoOats']],
  'hops-yanqi': ['春夏生长、初秋采收；二十七团的9月田间报道记录采花及加工，具体日期仍须按品种和球花成熟度判断。', ['yanqiHops', 'yanqiHopHarvest', 'hopSeason']],
  'hops-yumen': ['春夏攀藤生长，秋季采收；当地9月进入采摘加工高峰，晴好天气便于及时采花和后续干燥。', ['yumenHops', 'hopSeason']],
  'barley-yancheng': ['秋播越冬、春季生长，初夏按籽粒成熟度收获；籽粒啤用与青贮大麦采收阶段不同，不能混用收割日期。', ['yanchengBarley', 'chinaBarleyGuide']],
  'barley-hulunbuir': ['春末播种、夏季生长；东北内蒙古农技窗口约5月至6月上旬，当地8月已有麦收记录，按品种和蜡熟进度确定收期。', ['chinaBarleyGuide', 'hulunbuirHarvest']],
  'coffee-baoshan': ['当地12月和3月报道均记录咖啡采收，可见冬季至早春的采摘活动；这是历年现场观察，不能代替各海拔、品种的完整作期。', ['baoshanWinterHarvest', 'baoshanSpringHarvest'], 'regional_crop_observation'],
  'cocoa-xinglong': ['兴隆研究基地11月有成熟果采摘记录；热带多年生可可按成熟度分批采收，此记录不表示海南所有园区统一的全年采期。', ['xinglongCocoaHarvest'], 'regional_crop_observation'],
};

function region(id, type, nameZh, country, countryZh, continent, lat, lng, referencePlace, description, climateSummary, sourceIds, climateSourceIds) {
  const [seasonSummary, seasonSourceIds, seasonScope = 'regional_crop_calendar'] = SEASONS[id];
  return Object.freeze({
    id: `ingredient-${id}`, type, nameZh, country, countryZh, continent, lat, lng,
    locationPrecision: 'regional', locationRole: 'regional_reference',
    coordinateBasis: 'editorial_region_reference', referencePlace,
    coordinateNote: `${referencePlace}附近的区域示意点；一位小数经纬度，非农场或田块测量坐标。`,
    description, climateSummary, seasonSummary, seasonScope,
    climateScope: 'general_crop_guidance', supplyChainVerified: false,
    sourceUrls: Object.freeze(sourceIds.map(id => SOURCES[id])),
    climateSourceUrls: Object.freeze(climateSourceIds.map(id => SOURCES[id])),
    seasonSourceUrls: Object.freeze(seasonSourceIds.map(id => SOURCES[id])),
    checkedAt: INGREDIENT_REGION_NOTES.checkedAt,
  });
}

export const INGREDIENT_REGIONS = Object.freeze([
  region('barley-saskatchewan', 'barley', '萨斯喀彻温大麦区', 'Canada', '加拿大', 'North America', 52.1, -106.7, 'Saskatoon',
    '加拿大草原省份中的大麦产区；粮委报告明确区分制麦、食用与饲用大麦。',
    '偏凉生长季有利于谷物发育；灌浆期水分和热胁迫影响籽粒质量。', ['canadaBarley'], ['coolGrains', 'grainHeat']),
  region('barley-western-australia', 'barley', '西澳大麦种植带', 'Australia', '澳大利亚', 'Oceania', -33.3, 117.3, 'Wagin',
    '西澳谷物带种植制麦和饲用大麦，官方播种指南按区域比较品种表现。',
    '利用偏凉的生长季；品种与播期需兼顾水分、霜冻和后期高温。', ['waBarley'], ['waBarley', 'coolGrains']),
  region('barley-scotland', 'barley', '苏格兰大麦区', 'United Kingdom', '英国', 'Europe', 57.5, -2.6, 'Aberdeenshire',
    '苏格兰谷物生产以大麦为主，春大麦占重要位置；此点表示东北部种植区。',
    '偏凉季节适合春播谷物；收获质量仍受降雨和成熟时机影响。', ['scotlandBarley', 'scotlandMap'], ['coolGrains']),

  region('hops-yakima', 'hops', '雅基马谷啤酒花区', 'United States', '美国', 'North America', 46.6, -120.5, 'Yakima Valley',
    '华盛顿州雅基马谷是美国啤酒花的重要种植集中区，生长期常采用灌溉。',
    '长日照参与植株生长与开花调控；生长期需稳定供水，不能把干燥等同于无需灌溉。', ['yakima'], ['hopSeason', 'hopDaylight']),
  region('hops-hallertau', 'hops', '哈勒陶啤酒花区', 'Germany', '德国', 'Europe', 48.7, 11.8, 'Hallertau / Hüll',
    '巴伐利亚哈勒陶拥有成片啤酒花田和Hüll研究中心。',
    '温带长日照有利于生长；高温干旱和短时强降雨均会增加生产风险。', ['hallertau'], ['hallertau', 'hopDaylight']),
  region('hops-saaz', 'hops', '扎泰茨／萨兹啤酒花区', 'Czechia', '捷克', 'Europe', 50.3, 13.5, 'Žatec / Saaz',
    '欧赫热河附近的啤酒花田与扎泰茨共同形成持续耕作的萨兹种植景观。',
    '啤酒花依赖合适日照与生长季水分；产区条件不能仅由当天气温判断。', ['saaz'], ['hopDaylight', 'hopSeason']),
  region('hops-nelson', 'hops', '尼尔森—塔斯曼啤酒花区', 'New Zealand', '新西兰', 'Oceania', -41.3, 173.1, 'Nelson–Tasman / Waimea',
    '新西兰商业啤酒花集中在南岛北部的尼尔森与塔斯曼地区。',
    '温带日照节律配合生长季供水；需按南半球季节理解生长和采收。', ['nzHops', 'nzHopsRegions'], ['nzHopsRegions', 'hopDaylight']),

  region('wheat-kansas', 'wheat', '堪萨斯冬小麦区', 'United States', '美国', 'North America', 38.5, -98.8, 'Great Bend / central Kansas',
    'USDA统计确认堪萨斯大面积种植冬小麦；此处不代表某款啤酒采购来源。',
    '小麦是冷季谷物；春季水分及灌浆期热、旱胁迫会影响收成。', ['kansas'], ['grainHeat']),
  region('wheat-punjab', 'wheat', '旁遮普小麦区', 'India', '印度', 'Asia', 30.9, 75.8, 'Ludhiana / Punjab',
    '旁遮普农业大学在当地麦田开展应对成熟后期热胁迫的农技工作。',
    '偏凉生长季有利；成熟后期突升的温度可能缩短灌浆，播期与管理很重要。', ['punjab'], ['punjab', 'grainHeat']),
  region('wheat-nsw', 'wheat', '新南威尔士南部小麦区', 'Australia', '澳大利亚', 'Oceania', -35.1, 147.4, 'Wagga Wagga',
    '新南威尔士南部是冬季谷物产区，Wagga Wagga设有小麦播期和物候研究。',
    '生长季降雨与土壤储水重要；播期要避开开花期霜冻及后期干热风险。', ['nswWheat', 'nswSowing'], ['nswWheat', 'nswSowing']),

  region('oats-saskatchewan', 'oats', '萨斯喀彻温燕麦区', 'Canada', '加拿大', 'North America', 52.8, -104.6, 'Melfort / northeastern Saskatchewan',
    '省级农业统计记录东北部及其他分区的燕麦播种进度。',
    '燕麦适合偏凉生长季，对持续高温较敏感；需要合适土壤水分。', ['saskOats'], ['coolGrains', 'grainHeat']),
  region('oats-scotland', 'oats', '苏格兰燕麦区', 'United Kingdom', '英国', 'Europe', 56.4, -3.4, 'Perth / Scottish cereal belt',
    '燕麦列入苏格兰官方谷物收获统计；图中以Perth周边作为区域示意。',
    '偏凉天气有利于燕麦发育；湿润不等于可长期积水，热胁迫也会影响灌浆。', ['scotlandCrops', 'scotlandMap'], ['coolGrains', 'grainHeat']),
  region('oats-wa', 'oats', '西澳燕麦种植带', 'Australia', '澳大利亚', 'Oceania', -32.8, 116.8, 'Wandering / Western Australian wheatbelt',
    '西澳谷物带种植籽粒和干草用燕麦；用途和品种需分别核对。',
    '冷季生长，产区管理需考虑降雨不足与霜冻；不是全年同一适生条件。', ['waOats'], ['waOatsClimate']),

  region('rye-brandenburg', 'rye', '勃兰登堡黑麦区', 'Germany', '德国', 'Europe', 52.8, 13.2, 'central Brandenburg',
    '黑麦是勃兰登堡主要谷物之一，官方农报记录其种植和区域品种试验。',
    '黑麦可适应较贫瘠、偏干的区域条件；适应性不意味着没有干旱风险。', ['brandenburg', 'brandenburgTrials'], ['brandenburg']),
  region('rye-minnesota', 'rye', '明尼苏达黑麦种植区', 'United States', '美国', 'North America', 45.6, -95.9, 'Morris / western Minnesota',
    '当地农技资料涵盖冬黑麦谷物与覆盖作物；覆盖作物种植不等于酿造用粮。',
    '冬黑麦可在较冷条件下萌发并于春季恢复生长；品种和越冬条件仍重要。', ['minnesotaGrains'], ['ryeClimate']),

  region('citrus-valencia', 'citrus', '瓦伦西亚柑橘区', 'Spain', '西班牙', 'Europe', 39.2, -0.5, 'Ribera / Valencia',
    '瓦伦西亚官方作物统计列出橙、橘等柑橘种植；果皮可作为酿造辅料，未核验供应链。',
    '柑橘应避开严重冻害；土壤排水与旱期供水也是重要条件。', ['valencia'], ['citrusSites', 'citrusCold']),
  region('citrus-florida', 'citrus', '佛罗里达中南部柑橘区', 'United States', '美国', 'North America', 27.6, -81.5, 'Highlands County / Lake Wales Ridge',
    '佛罗里达柑橘种植主要向半岛中南部集中，此点是区域示意而非果园。',
    '较暖地点可降低冻害风险，但仍需防寒；灌溉和排水要结合当地土壤。', ['citrusSites'], ['citrusSites', 'citrusCold']),

  region('coriander-kota', 'coriander', '科塔—拉姆甘杰曼迪芫荽区', 'India', '印度', 'Asia', 24.7, 75.9, 'Ramganj Mandi / Kota',
    '拉贾斯坦农业项目报告将科塔列为芫荽种植地区；香料局在当地设有种子香料加工设施。',
    '印度农技指南强调较凉、相对干燥和无霜的生长期，具体播季需按当地确定。', ['kotaGrowing', 'kota'], ['corianderIndia']),
  region('coriander-saskatchewan', 'coriander', '萨斯喀彻温芫荽区', 'Canada', '加拿大', 'North America', 52.2, -105.1, 'Humboldt / Saskatchewan',
    '省农业厅记录当地大粒与小粒芫荽种植、育种和加工；图示为区域参考。',
    '当地多作春播香料作物；花期过热干旱或凉湿病害天气都可能造成损失。', ['corianderCanada'], ['corianderCanada']),

  region('coffee-minas', 'coffee', '米纳斯吉拉斯咖啡区', 'Brazil', '巴西', 'South America', -21.6, -45.4, 'Varginha / southern Minas Gerais',
    '米纳斯吉拉斯农业推广机构记录当地咖啡生产，南部高地是代表性种植区。',
    '阿拉比卡偏好较温和的热带高地条件；持续增温和降水变化会影响适种性。', ['minas'], ['coffeeClimate']),
  region('coffee-sidama', 'coffee', '西达莫咖啡区', 'Ethiopia', '埃塞俄比亚', 'Africa', 6.7, 38.4, 'Sidama highlands',
    '国际咖啡组织气候研究列出传统Sidamo咖啡产区；示意点不表示现行行政边界。',
    '高地阿拉比卡对温度与降雨变化敏感；海拔不能单独决定豆子质量。', ['coffeeClimate'], ['coffeeClimate']),
  region('coffee-daklak', 'coffee', '得乐／邦美蜀咖啡区', 'Vietnam', '越南', 'Asia', 12.7, 108.1, 'Buôn Ma Thuột / Đắk Lắk',
    '越南知识产权主管机构确认邦美蜀咖啡的地理标志与得乐产区。',
    '罗布斯塔相对耐热，但降雨分布和年内温度变化仍影响生产。', ['dakLak'], ['coffeeClimate']),
  region('coffee-puer', 'coffee', '云南普洱咖啡区', 'China', '中国', 'Asia', 22.8, 100.9, 'Pu’er / Simao',
    '云南省政府与农业部门明确记录普洱的咖啡种植及品种推广。',
    '阿拉比卡需要相对温和的热带山地环境；实际适生性还受降雨和品种影响。', ['puer', 'yunnanCoffee'], ['coffeeClimate']),

  region('cocoa-ghana', 'cocoa', '塞夫维维奥索可可区', 'Ghana', '加纳', 'Africa', 6.2, -2.5, 'Sefwi Wiawso / Western North',
    '加纳可可局列出Western North可可分区，包括Sefwi Wiawso周边。',
    '可可适合温暖湿润环境，需要较均匀供水；持续缺水会限制生长。', ['ghana', 'ghanaWest'], ['cocoaClimate']),
  region('cocoa-soubre', 'cocoa', '苏布雷可可区', 'Côte d’Ivoire', '科特迪瓦', 'Africa', 5.8, -6.6, 'Soubré / Nawa',
    '国家农村发展支持机构与咖啡可可委员会在苏布雷地区开展可可园技术工作。',
    '温暖湿润有利于可可；降雨分布、干季长度及树荫管理都重要。', ['soubre'], ['cocoaClimate']),
  region('cocoa-losrios', 'cocoa', '洛斯里奥斯可可区', 'Ecuador', '厄瓜多尔', 'South America', -1.0, -79.5, 'Quevedo / Los Ríos',
    '厄瓜多尔国家农业研究院将洛斯里奥斯列为可可种植省份。',
    '可可偏好温暖湿润、较稳定的供水；季节性缺水与强烈曝晒需结合当地管理。', ['ecuador'], ['cocoaClimate']),

  // Additional sparse-region references. Broad crop statistics confirm the
  // region, not the exact field under this rounded editorial map anchor.
  region('barley-akmola', 'barley', '阿克莫拉春大麦区', 'Kazakhstan', '哈萨克斯坦', 'Asia', 51.7, 71.0, 'Shortandy / Akmola',
    '哈萨克斯坦官方统计记录阿克莫拉大麦种植；绍尔坦德的巴拉耶夫粮作中心发布该州春耕技术指南。是否达到制麦用途需另验品种和质量。',
    '春播冷季谷物需利用土壤储水；区域农技资料强调夏季降雨不均、干热风及秋季霜冻风险。', ['akmolaBarley', 'akmolaGrainGuide'], ['akmolaGrainGuide']),
  region('oats-novosibirsk', 'oats', '新西伯利亚燕麦区', 'Russia', '俄罗斯', 'Asia', 55.0, 82.2, 'Kochenevo / Novosibirsk Oblast',
    '俄罗斯农业分析中心的区域播种报告明确记录新西伯利亚州春燕麦；科切尼奥沃附近仅作州内示意点，不代表酿酒供应田。',
    '燕麦适合偏凉生长季；持续高温和灌浆期水分不足会影响籽粒，实际播期需结合当地春季条件。', ['novosibirskOats'], ['coolGrains', 'grainHeat']),
  region('hops-george', 'hops', '乔治—奥特尼夸啤酒花区', 'South Africa', '南非', 'Africa', -33.9, 22.4, 'George / Outeniqua',
    '南非农业部门记录乔治周边啤酒花农场及采收季；此处展示已存在的非洲种植区，不将其绑定到地图上的酒厂。',
    '生长季需要可靠供水；奥特尼夸集水区的缺水与外来植被耗水会影响当地农场，不能把日照充足等同于无需灌溉。', ['georgeHops'], ['georgeWater', 'hopSeason']),
  region('citrus-harvey', 'citrus', '西澳哈维柑橘区', 'Australia', '澳大利亚', 'Oceania', -33.1, 115.9, 'Harvey / Western Australia',
    '哈维地方政府资料记录当地橙、柑和其他柑橘生产；该点表示西澳西南部果园区，果皮是否用于酿酒仍需逐款证据。',
    '地中海型气候配合壤土与灌溉供水支持柑橘生产；夏季水分管理仍重要，湿润季节也需注意排水。', ['harveyCitrus'], ['harveyCitrus', 'citrusSites']),
  region('hops-elbolson', 'hops', '埃尔博尔松啤酒花区', 'Argentina', '阿根廷', 'South America', -42.0, -71.5, 'El Bolsón / Río Negro',
    '里奥内格罗省政府记录埃尔博尔松商业啤酒花田和品种采收，属于巴塔哥尼亚的真实种植区域。',
    '山谷地形减弱强风，夏季长日照与凉爽夜间有利于生长；热天仍需灌溉，采收和干燥受降雨影响。', ['elBolsonHops'], ['elBolsonClimate', 'elBolsonHops']),
  region('oats-passofundo', 'oats', '帕苏丰杜白燕麦区', 'Brazil', '巴西', 'South America', -28.3, -52.4, 'Passo Fundo / Rio Grande do Sul',
    '帕苏丰杜大学开展白燕麦田间研究，论文由Embrapa知识库保存；图中表示南里奥格兰德州种植与农艺研究区域。',
    '当地为湿润亚热带环境，白燕麦利用较凉的秋冬生长季；品种和播期会改变成熟过程及病害风险。', ['passoFundoOats'], ['passoFundoOats', 'coolGrains']),

  // Chinese additions distinguish crop-growing evidence from named beer
  // sourcing. Rounded anchors illustrate regions, not individual farms.
  region('hops-yanqi', 'hops', '新疆焉耆盆地啤酒花区', 'China', '中国', 'Asia', 42.0, 86.5, 'Yanqi Basin / 27th Regiment Tianhu area',
    '焉耆盆地的二十七团长期种植啤酒花，农业报道和采收现场照片均有记录；示意点表示焉耆、博湖之间的种植区域。',
    '啤酒花生长受长日照节律影响，生长季仍需稳定供水；西北干燥条件不能等同于无需灌溉。', ['yanqiHops', 'yanqiHopHarvest', 'yanqiLocation'], ['hopSeason', 'hopDaylight']),
  region('hops-yumen', 'hops', '甘肃玉门啤酒花区', 'China', '中国', 'Asia', 40.3, 97.0, 'Yumen Town / Hexi Corridor',
    '玉门镇有实际啤酒花种植与采摘加工；本点表示河西走廊玉门周边产区，不是玉门老市区或某家酒厂。',
    '当地日照较长、昼夜温差大、降水少；啤酒花旺长期的供水管理仍重要，采收干燥需结合天气。', ['yumenHops'], ['yumenHops', 'hopSeason']),
  region('barley-yancheng', 'barley', '江苏盐城啤酒大麦区', 'China', '中国', 'Asia', 33.4, 120.1, 'Yancheng / coastal Jiangsu',
    '盐城农业部门记录当地籽粒啤酒大麦、青贮大麦及示范种植；只有适用品种和达标籽粒才能进入制麦用途。',
    '秋冬播谷物利用凉季生长；春季水分影响抽穗灌浆，成熟与收储需避免雨淋、穗发芽和霉变。', ['yanchengBarley'], ['chinaBarleyGuide']),
  region('barley-hulunbuir', 'barley', '呼伦贝尔拉布大林春大麦区', 'China', '中国', 'Asia', 50.2, 120.2, 'Labudalin / Erguna / Hulunbuir',
    '拉布大林农牧场有已公开的啤酒大麦标准化种植项目；这里展示真实作物产区，不将项目供应关系套用到地图内其他酒款。',
    '高纬地区应选适应当地的早熟春性品种，利用解冻后的土壤水分；抽穗灌浆及收获期的水分管理影响籽粒质量。', ['hulunbuirBarley', 'hulunbuirHarvest'], ['chinaBarleyGuide']),
  region('coffee-baoshan', 'coffee', '云南保山潞江咖啡区', 'China', '中国', 'Asia', 25.0, 98.9, 'Lujiang Valley / Longyang / Baoshan',
    '云南农业部门明确记录保山隆阳潞江的小粒咖啡种植；与普洱是不同的区域示意点，不表示所有地块或固定采购链。',
    '阿拉比卡的适生性受温度、降雨分布、海拔和品种共同影响；河谷不同高度条件差异明显，不能用当天温度打分。', ['baoshanCoffee'], ['coffeeClimate']),
  region('cocoa-xinglong', 'cocoa', '海南兴隆可可示范种植区', 'China', '中国', 'Asia', 18.7, 110.2, 'Xinglong / Wanning / Hainan',
    '中国热带农业科学院香饮所在万宁兴隆开展可可育种、示范种植和加工；此处标为示范产区，不将试验规模夸大为全球主产区。',
    '可可需要温暖湿润、相对稳定的水分环境；旱期供水与树荫管理重要，海南局地条件和品种仍需单独判断。', ['xinglongCocoa', 'xinglongCocoaHarvest'], ['cocoaClimate']),

  // Additional researched growing regions; product recommendations remain
  // discovery links, not evidence of a brewery's ingredient supply chain.
  region('hops-tono', 'hops', '岩手远野啤酒花区', 'Japan', '日本', 'Asia', 39.3, 141.5, 'Tono / Iwate',
    '岩手县远野有长期啤酒花栽培，麒麟公开记录当地种植者、酒花田与采收；不将特定品牌的采购关系延伸到推荐酒款。',
    '温带日照节律参与酒花生长与开花，春夏生长需要稳定供水；采收按球花成熟度而非单日气温决定。', ['tonoHops', 'tonoHarvest'], ['hopDaylight', 'hopSeason']),
  region('citrus-limpopo', 'citrus', '林波波柑橘种植区', 'South Africa', '南非', 'Africa', -23.9, 30.4, 'Tzaneen / Mopani / Limpopo',
    '林波波省农业资料确认Valencia橙是当地重要作物；以Mopani地区Tzaneen附近示意种植区，果皮可作为酿造辅料。',
    '橙类适合温暖生长期，需防范霜冻并管理供水；不同品种和地块的耐寒性、成熟期并不相同。', ['limpopoCitrus'], ['limpopoCitrus', 'citrusCold']),
  region('barley-arsi', 'barley', '阿尔西高地大麦区', 'Ethiopia', '埃塞俄比亚', 'Africa', 7.9, 39.1, 'Asella / Arsi highlands',
    'ICARDA记录阿塞拉农户种植改良制麦大麦，阿尔西也种植食用大麦；并非当地所有大麦都达到制麦要求。',
    '高地较凉生长条件适合大麦；灌浆期间水分及热胁迫影响籽粒表现，品种选择需结合海拔与降雨。', ['arsiBarley', 'arsiSeason'], ['coolGrains', 'grainHeat']),
  region('barley-buenosaires', 'barley', '南布宜诺斯艾利斯大麦区', 'Argentina', '阿根廷', 'South America', -38.3, -60.2, 'Tres Arroyos / southern Buenos Aires',
    '阿根廷INTA记录布宜诺斯艾利斯省南部的大麦栽培和品种播期；适用品种及达标籽粒可用于制麦，不能等同全部用于啤酒。',
    '秋冬播种利用南半球凉季，冬春水分及成熟期热、旱胁迫影响品质；播期按早晚熟品种调整。', ['buenosAiresBarley'], ['buenosAiresBarley', 'grainHeat']),
  region('coffee-huila', 'coffee', '乌伊拉山地咖啡区', 'Colombia', '哥伦比亚', 'South America', 1.9, -76.1, 'Pitalito / Huila',
    '哥伦比亚咖啡种植者联合会在乌伊拉持续记录生产与采收；以Pitalito周边山地作区域示意，咖啡为可选酿造辅料。',
    '阿拉比卡受海拔、温度与雨季分布共同影响；花期和果实成熟会随降雨变化，应按海拔分区理解。', ['huilaCoffee'], ['coffeeClimate']),
  region('cocoa-sanmartin', 'cocoa', '圣马丁热带可可区', 'Peru', '秘鲁', 'South America', -6.6, -76.1, 'Chazuta / San Martín',
    '秘鲁农业部门确认圣马丁可可种植，气象机构在Chazuta等站记录实地物候；本点不代表所有种植园或任何酒厂供货范围。',
    '可可需要温暖湿润及较稳定的水分，过度干旱会影响坐果和成熟；遮荫、排水与降雨分布同样重要。', ['sanMartinCocoa', 'sanMartinSeason'], ['cocoaClimate']),
  region('wheat-altai', 'wheat', '阿尔泰边疆区小麦种植带', 'Russia', '俄罗斯', 'Asia', 52.8, 82.8, 'Aleysk / Altai Krai',
    '俄罗斯农业分析中心记录阿尔泰边疆区软质、硬质小麦生产；示意点位于阿列伊斯克周边农区，谷物不默认全部用于酿酒。',
    '春播谷物利用偏凉生长季；抽穗灌浆水分和短时高温影响质量，干旱地区需结合土壤储水安排管理。', ['altaiWheat', 'altaiHarvest'], ['coolGrains', 'grainHeat']),
  region('coffee-rwenzori', 'coffee', '鲁文佐里山地咖啡区', 'Uganda', '乌干达', 'Africa', 0.3, 30.0, 'Kasese / eastern Rwenzori slopes',
    '乌干达咖啡发展局公开的供应商资料列明鲁文佐里山地阿拉比卡咖啡及当地采收期；区域示意点位于乌干达一侧山麓。',
    '山地阿拉比卡适生性受海拔、温度及雨季影响；成熟不齐时需分批采熟果，不能将全国气候套用到每座山坡。', ['rwenzoriCoffee'], ['coffeeClimate']),
]);
